all:
  hosts:
    tabletopnode1:
      ansible_host: 10.5.0.101
    tabletopnode2:
      ansible_host: 10.5.0.102
    tabletopnode3:
      ansible_host: 10.5.0.103

  children:
    new_vaults:
      hosts:
        tabletopnode1:
        tabletopnode2:
        tabletopnode3:

    remove_vaults:
      hosts:
        tabletopnode1:
        tabletopnode2:
        tabletopnode3:
