- name: Create MongoDB data/log directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ mongo_vault_agent_group }}"
    mode: "0750"
  loop:
    - "{{ mongo_base_dir }}/config/data"
    - "{{ mongo_base_dir }}/config/logs"
    - "{{ mongo_base_dir }}/config/conf"

- name: Disable transparent hugepage defragmentation
  become: true
  shell: |
    echo 'defer+madvise' > /sys/kernel/mm/transparent_hugepage/defrag

- name: Disable transparent hugepage paging
  become: true
  shell: |
    echo '0' > /sys/kernel/mm/transparent_hugepage/khugepaged/max_ptes_none

- name: Tune vm.swappiness to 1 (avoid swapping)
  become: true
  sysctl:
    name: vm.swappiness
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Render mongod “auth” config file
  template:
    src: mongod.conf.j2
    dest: "{{ mongo_base_dir }}/config/conf/mongod.conf"
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ mongo_vault_agent_group }}"
    mode: "0440"

- name: Create systemd service file for MongoDB config server
  copy:
    dest: /etc/systemd/system/mongod-configsvr.service
    content: |
      [Unit]
      Description=MongoDB Config Server
      After=network.target mongo-config-vault-agent.service
      Requires=mongo-config-vault-agent.service

      [Service]
      Type=simple
      User={{ mongo_vault_agent_user }}
      Group={{ mongo_vault_agent_group }}
      WorkingDirectory={{ mongo_base_dir }}
      LimitNOFILE=64000
      Environment=GLIBC_TUNABLES=glibc.pthread.rseq=0
      ExecStart={{ mongo_base_dir }}/bin/mongod \
        --config "{{ mongo_base_dir }}/config/conf/mongod.conf"
      Restart=always
      RestartSec=5

      [Install]
      WantedBy=multi-user.target
  notify:
    - Reload systemd

- name: Force systemd reexec and daemon reload
  shell: |
    systemctl daemon-reexec
    systemctl daemon-reload

- name: Check if mongod-configsvr.service unit exists
  stat:
    path: /etc/systemd/system/mongod-configsvr.service
  register: mongod_unit

- name: Reset failed mongod-configsvr if loaded
  command: systemctl reset-failed mongod-configsvr.service
  when: mongod_unit.stat.exists
  ignore_errors: true

- name: Enable and start MongoDB config server service
  systemd:
    name: mongod-configsvr.service
    enabled: yes
    state: started

- name: Fix ownership of all MongoDB files
  become: true
  file:
    path: "{{ mongo_base_dir }}/config"
    recurse: yes
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ mongo_vault_agent_group }}"
  notify:
    - Reload systemd

- name: Wait for MongoDB port to be open
  wait_for:
    host: "10.{{ mongo_config_subnet }}.0.{{ ansible_host.split('.')[-1] }}"
    port: "{{ config_port }}"
    timeout: 60
    delay: 5
  ignore_errors: true
