# Vault
- name: Create {{ vault_dir }}/secrets/mongo/shard directory
  file:
    path: "{{ vault_dir }}/secrets/mongo/shard"
    state: directory
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ vault_agent_navigational_group }}"
    mode: "0710"

- name: Create {{ vault_dir }}/scripts/mongo/shard directory
  file:
    path: "{{ vault_dir }}/scripts/mongo/shard"
    state: directory
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ vault_agent_navigational_group }}"
    mode: "0710"

- name: Create {{ vault_dir }}/templates/mongo/shard directory
  file:
    path: "{{ vault_dir }}/templates/mongo/shard"
    state: directory
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ vault_agent_navigational_group }}"
    mode: "0710"

- name: Create {{ vault_dir }}/agents/mongo/shard directory
  file:
    path: "{{ vault_dir }}/agents/mongo/shard"
    state: directory
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ vault_agent_navigational_group }}"
    mode: "0710"
