- name: Set up new Config Servers - Server Set up
  hosts: new_config_servers
  become: true
  vars_prompt:
    - name: vault_token
      prompt: "Enter Vault access token"
      private: true
    - name: ca_key_password
      prompt: "Enter CA key password"
      private: true
  vars_files:
    - ../vars/share.yaml
  roles:
    - role: share
    - role: share-config
    - role: apparmor-mongod
    - role: apparmor-mongosh
    - role: add-new-config-servers

- name: Set up new Config Servers - add to replica set
  hosts: tableTopNode2
  become: true
  vars_prompt:
    - name: vault_token
      prompt: "Enter Vault access token"
      private: true
  vars_files:
    - ../vars/share.yaml
  roles:
    - role: add-new-config-servers-add-to-replica-set
