- name: Set up Config Servers - Remove from replica
  hosts: tableTopNode1
  become: true
  run_once: true
  vars_prompt:
    - name: vault_token
      prompt: "Enter Vault access token"
      private: true
  vars_files:
    - ../vars/share.yaml
  roles:
    - role: remove-config-servers-from-replica

- name: Set up Config Servers - Clean up
  hosts: remove_config_servers
  become: true
  run_once: true
  vars_prompt:
    - name: vault_token
      prompt: "Enter Vault access token"
      private: true
  vars_files:
    - ../vars/share.yaml
  roles:
    - role: remove-config-servers-cleanup
