- name: Check if mongos role exists
  community.hashi_vault.vault_read:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    path: "pki/roles/mongos-10.{{ mongo_mongos_subnet }}.0.{{ ansible_host.split('.')[-1] }}"
  register: mongos_role
  environment:
    REQUESTS_CA_BUNDLE: "{{ local_ca_path }}"
  delegate_to: localhost
  ignore_errors: true

- name: Define PKI role for mongos certs
  community.hashi_vault.vault_write:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    mount_point: "pki"
    path: "pki/roles/mongos-10.{{ mongo_mongos_subnet }}.0.{{ ansible_host.split('.')[-1] }}"
    data:
      name: "mongos-10.{{ mongo_mongos_subnet }}.0.{{ ansible_host.split('.')[-1] }}"
      allowed_domains:
        - "{{ inventory_hostname | lower }}"
        - "{{ inventory_hostname }}.mongo.mongos"
        - "10.{{ mongo_mongos_subnet }}.0.{{ ansible_host.split('.')[-1] }}"
      key_type: "rsa"
      key_bits: 4096
      country:
        - "{{ cert_country }}"
      province:
        - "{{ cert_state }}"
      locality:
        - "{{ cert_locality }}"
      organization:
        - "{{ cert_organization }}"
      ou:
        - "{{ mongos_cert_ou }}"
      common_name: "{{ inventory_hostname }}.mongo.mongos"
      exclude_cn_from_sans: true
      allow_bare_domains: true
      alt_names:
        - "{{ inventory_hostname | lower }}"
        - "{{ inventory_hostname }}.mongo.mongos"
      ip_sans:
        - "10.{{ mongo_mongos_subnet }}.0.{{ ansible_host.split('.')[-1] }}"
      allow_ip_sans: true
      allow_localhost: false
      server_flag: true
      client_flag: true
      key_usage:
        - DigitalSignature
        - KeyEncipherment
      ext_key_usage:
        - server_auth
        - client_auth
      ttl: "12h"
      max_ttl: "12h"
      renew_before: "1h"
  environment:
    REQUESTS_CA_BUNDLE: "{{ local_ca_path }}"
  delegate_to: localhost
  when: mongos_role.failed or mongos_role.data is not defined
  no_log: true
