# Vault bin
- name: Set vault apparmor profile name
  set_fact:
    vault_apparmor_profile_name: "{{ vault_dir | regex_replace('^/', '') | replace('/', '.') }}.bin.vault"

- name: Ensure AppArmor rule exists for Vault's Snowflake OCSP cache
  lineinfile:
    path: /etc/apparmor.d/{{ vault_apparmor_profile_name }}
    line: "  /home/{{ mongo_vault_agent_user }}/.cache/snowflake/ocsp_response_cache.json rwk,"
    state: present
    insertbefore: '^\}'
    create: no
  ignore_errors: true

- name: Re-parse the AppArmor profile
  command: apparmor_parser -r /etc/apparmor.d/{{ vault_apparmor_profile_name }}
  ignore_errors: true

- name: Re-enforce the profile
  command: aa-enforce {{ vault_apparmor_profile_name }}
  ignore_errors: true
