- name: Add sudoers rule for {{ mongo_vault_agent_user }} to run restart script
  copy:
    dest: /etc/sudoers.d/{{ mongo_vault_agent_user }}-mongo
    content: |
      {{ vault_agent_user }} ALL=(ALL) NOPASSWD: \
        {{ vault_dir }}/scripts/mongo/config/mongo-config-vault-restart.sh, \
        {{ vault_dir }}/scripts/mongo/shard/mongo-shard-vault-restart.sh, \
        {{ vault_dir }}/scripts/mongo/mongos/mongos-vault-restart.sh, \
        /bin/systemctl restart mongod-configsvr.service, \
        /bin/systemctl restart mongos.service, \
        /bin/systemctl restart mongod-shardsvr.service
    owner: root
    group: root
    mode: "0440"
