- name: Install required AppArmor packages
  apt:
    name:
      - apparmor
      - apparmor-utils
      - apparmor-profiles
      - apparmor-profiles-extra
    state: present
    update_cache: yes
  become: true
