- name: Check if mongod log exists
  ansible.builtin.stat:
    path: "{{ mongo_base_dir }}/shard/logs/mongod.log"
  register: mongod_log_exists

- name: Truncate mongod log safely
  ansible.builtin.command: truncate -s 0 {{ mongo_base_dir }}/shard/logs/mongod.log
  become: true
  when: mongod_log_exists.stat.exists
  tags: truncate

- name: Restart mongod-shardsvr service
  ansible.builtin.systemd:
    name: mongod-shardsvr.service
    state: restarted
  become: true
